### ISSUE TITLE
Circular loader - Only progress bar.

### ISSUE THREAD

**Issue by tarang9211** [andy9775/React-Native-CircularProgress#8]
I've been trying to get only the progress bar to show up with the component's backgroundColor set to `transparent`. Could you provide some guidance as to how you achieved this in your .gif example?

**Comment by andy9775** [comment]
Hey, so in the gif examples I didn't use transparent, I used the actual color of the background that the component was in. This gives the illusion of being transparent. The reason this can't be done is because the component is actually made up of two rectangles which rotate around either exposing or hiding one another.
